[phases.setup]
nixPkgs = ["python3", "pip", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p templates static logs data"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 60 app:app"

[variables]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
